source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.4'

gem 'active_skin'
gem 'activeadmin', '>= 2.11.0'
gem 'activeadmin_addons', '>= 1.8.2'
gem 'activeadmin_reorderable'
gem 'acts-as-taggable-on', '~> 6.0'
gem 'acts_as_list'
gem 'bootsnap', '>= 1.1.0', require: false
gem 'carrierwave'
gem 'coffee-rails', '~> 5.0.0'
gem 'devise', '>= 4.7.2'
gem 'devise-i18n', '>= 1.9.0'
gem 'exception_notification', '>= 4.5.0'
gem 'faker'
gem 'fcm'
gem 'figaro'
gem 'jbuilder', github: 'rails/jbuilder', branch: 'master'
gem 'jquery-rails', '>= 4.4.0'
gem 'jquery-ui-rails', '>= 7.0.0'
gem 'mini_magick'
gem 'ordinare'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'
gem 'rails-i18n', '>= 7.0.1'
gem 'railroady'
gem 'sass-rails', '~> 6.0', '>= 6.0.0'
gem 'sendgrid-ruby'
gem 'sendgrid-actionmailer'
gem 'tinymce-rails', '>= 4.9.7'
gem 'tinymce-rails-imageupload', '~> 4.0.0.beta'
gem 'uglifier', '>= 1.3.0'
gem 'redis', '~> 3.0'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails'
  gem 'rails-erd'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 4.0.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem "capistrano", "~> 3.11"
  gem 'capistrano-passenger', '~> 0.2.0'
  gem 'capistrano-rails', '~> 1.2'
  gem 'capistrano-rbenv', '~> 2.1'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara', '>= 3.30.0'
  gem 'chromedriver-helper'
  gem 'selenium-webdriver'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
